### ISSUE TITLE
Local scopes

### ISSUE THREAD

**Issue by nchanged** [dsherret/ts-morph#640] opened 2019-05-31 18:29 UTC
Hi, here I have another question or a feature request ;-)

Let's take a look at this snippet:

```ts
import { bar } from "./foo"
function foo(bar) {
  console.log(bar);
}
foo(bar);
```

In this example I would like to trace down all `bar` variables, but the ones that belong to the root scope (modules' body). Ideally when capturing all Identifiers I would check whether it has been defined locally (in case of where it's inside the function `foo`) and skip any transformations. Another example:

```
function World(){
   Hello();
}
function Hello(){}

World();
```

How one would tell that `Hello` has been actually defined, or will be defined statically in the context, when inside the `World` function scope.

I have implemented (it's in a WIP state)  a similar functionality with a conventional AST. To give you an idea, see [here](https://github.com/fuse-box/fuse-box/blob/v4/src/utils/ast.ts#L21-L65) But it doesn't cover the second scenario, unfortunately.

Thanks!

UPD.

It looks like `id.findReferences()` is the right way to go?! Find references that point to that original import.

**Comment by dsherret** [comment] 2019-05-31 19:27
Hey @nchanged, if you get the identifier's symbol (`id.getSymbol()`) you can use `Symbol#getDeclarations()` to see where it's defined. I believe that's all you'll have to do.

See putting that code in [ts-ast-viewer.com](https://ts-ast-viewer.com), click on the identifiers, then look at the "Symbol" section.

Some other features coming in v3.0 (hopefully released within the next couple of weeks) that might be helpful:

* https://github.com/dsherret/ts-morph/issues/561#issuecomment-493704673
* https://github.com/dsherret/ts-morph/issues/310#issuecomment-493790284

**Comment by nchanged** [comment] 2019-05-31 19:38
@dsherret awesome! I started playing around with it, however, I've found a bug

```
var process = {};
console.log(process.env.NODE_ENV);
```

It gives me `NodeJS.Process`
The things is, I've seen a LOT of cases, where people just override it.

**Comment by dsherret** [comment] 2019-05-31 20:04
@nchanged it doesn't also return that local declaration?

I feel like when using `var` (not `let` or `const`) it would return both that variable declaration and the `NodeJS.Process` in the array. That's basically all compiler API code so I'd be very surprised if there was a bug in that.

**Comment by nchanged** [comment] 2019-05-31 20:05
Actually, here is another one (please correct me if I am wrong)

```
console.log(process.env.NODE_ENV);
var process = {};
console.log(process.env.NODE_ENV);
```

The first one, gives a wrong symbol or reference for the first expression (should give none) but refers to the declaration on the second line

**Comment by dsherret** [comment] 2019-05-31 20:09
@nchanged is it still referencing `NodeJS.Process` when using `const` though? Also, when using `var` does it list both `NodeJS.Process` and the variable declaration in `#getDeclarations()`?

**Comment by dsherret** [comment] 2019-05-31 20:12
Also, doesn't `#getDeclarations()` at least always return the local declaration?

**Comment by nchanged** [comment] 2019-05-31 20:12
```
id.getSymbol()
              .getDeclarations()
              .forEach(r => {
                console.log(r.getText());
              });
```

All referencing that `const`

If I change it to `var` it start referencing `NodeJS.Process` too + that variable. And In both cases which is super odd

**Comment by dsherret** [comment] 2019-05-31 20:25
I think the `process` above `const` referencing the variable declaration is expected behaviour. I get a runtime error when running the following code in node.js when using `const`, but no error when using `var` (since `var` is hoisted):

```js
console.log(process); // error here because it's using process before it's declaration
const process = {};
console.log(process);
```

Also, TypeScript's language service goes to the variable declaration when doing "go to definition".

When using `var`, I'm not sure why the compiler API returns `NodeJS.Process` as well, but as you mentioned, you can see the local declaration in the results.

**Comment by nchanged** [comment] 2019-05-31 20:30
Let's just forget for a second the `process`

```
console.log(foo.bar);
const foo = {};
console.log(foo.bar);
```

Gives the same weird result. First line - `foo` is undefined, however, it's successfully linked the the constant..

**Comment by dsherret** [comment] 2019-05-31 20:31
@nchanged I think `var` returns both declarations because it's legal to do this:

```ts
var p: string;
var p: string;
```

Unlike with `const` or `let`. So probably something similar is happening with `process`. Anyway, this is making more sense to me and seems like expected behaviour.

**Comment by dsherret** [comment] 2019-05-31 20:32
@nchanged that example with `foo` pointing to the declaration makes sense. It is referring to the variable declaration:

![image](https://user-images.githubusercontent.com/1609021/58733154-a9ab1880-83c1-11e9-851a-e48f47474c05.png)

**Comment by nchanged** [comment] 2019-05-31 20:36
I understand that, but `foo` could be a global variable, and with `var` it would give me wrong results.
That's what I am trying to figure out. How to detect **valid** references...

**Comment by dsherret** [comment] 2019-05-31 20:47
> foo could be a global variable

No, not in that context. `foo` is referring to the variable declaration on the line below. It seems all declarations are hoisted in JavaScript, but `let` and `const` declarations can't be used before they're initialized. Read more here: https://stackoverflow.com/a/31222689/188246

> with `var` it would give me wrong results

That seems to be the case, but you should be able to evaluate what the best match is. Perhaps it returns the multiple declarations because `var` is not block scoped, but I'm not sure.

**Comment by dsherret** [comment] 2019-06-01 00:15
By the way, just to reinforce this point, the following code:

```js
console.log(process.bar);
const process = {};
console.log(process.bar);
```

Throws the following error in node.js at runtime (though I think it should return a more specific error... same one happens with `foo`):

```
ReferenceError: process is not defined
```

But once the declaration is removed it runs fine.

**Comment by nchanged** [comment] 2019-06-01 05:30
Thank you! Then I will just rely on it. It's just I have seen so many weird scenarios (being a maintainer of a js bundler) just wanted to be sure :)

**Closed** 2021-04-03 17:15 UTC
Labels: question
