### ISSUE TITLE
How to get non-qualified type text?

### ISSUE THREAD

**Issue by elclanrs** [dsherret/ts-morph#450] opened 2018-10-03 15:09 UTC
I'm not sure what changed in my setup, perhaps a TypeScript upgrade, or a ts-simple-ast upgrade, but today I noticed that my script no longer works as intended, and when I get the text of the type of a class property I get an import path in front of it.

I wasn't able to find how to just get the non-qualified type. I must be missing something basic. Any help is appreciated.

This is my code:

```javascript
const properties = _(cls.getInstanceProperties())
  .filter(prop => {
    return prop.getKind() === ts.SyntaxKind.PropertyDeclaration;
  })
  .forEach(prop => {
    console.log(prop.getType().getText());
```

The above outputs qualified types for some of the properties:

```
import("/path/to/node_modules/@angular/core/src/event_emitter").EventEmitter<Event>
```

But previously I was just getting:

```
EventEmitter<Event>
```

How can I get the latter again?

**Comment by Gerrit0** [comment] 2018-10-03 15:20
I believe this would have changed as of TS 2.9, when [import types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html) was introduced. Sorry - not sure how to get back to the original behavior...

**Comment by elclanrs** [comment] 2018-10-03 15:27
@dsherret Thank you for the quick response! I was about to do some string manipulation but this solution is perfect.

**Comment by dsherret** [comment] 2018-10-03 15:28
@elclanrs and thanks for asking! I was actually using string manipulation in some of my other code to get rid of it, but now I'll change that code to this 😄

**Comment by elclanrs** [comment] 2018-10-24 07:37
This broke again in my project and that workaround is not working anymore as it is showing the full qualified import again.

Can anybody confirm that this is the case? I'm running ts-simple-ast@17.1.1 and typescript@2.9.2

If this is the case, is string manipulation the only way around it?

**Comment by dsherret** [comment] 2018-10-24 16:35
@elclanrs what typescript compiler api version are you using?

Run this to check:

```ts
import { ts } from "ts-simple-ast";

console.log(ts.version);
```

**Comment by dsherret** [comment] 2018-10-24 16:40
@elclanrs I tested this with ts 3.0.1, 3.0.3, 3.1.1, and 3.1.3 and it worked fine. Could you provide some reproduction steps and let me know what compiler version it's using?

```ts
import { Project, TypeFormatFlags } from "ts-simple-ast";

const project = new Project({ useVirtualFileSystem: true });
const sourceFile = project.createSourceFile("Class.ts", "export class Class { prop: string; }");
const mainFile = project.createSourceFile("main.ts", "import { Class } from './Class'; let c: Class;");

const varDec = mainFile.getVariableDeclarationOrThrow("c");
console.log(varDec.getType().getText()); // outputs: import("/Class").Class
console.log(varDec.getType().getText(varDec)); // outputs: Class
```

**Comment by elclanrs** [comment] 2018-10-24 16:55
Damn, it is working in isolation, but not in my project. I even went back to the exact commit where I made the change, removed node_modules and reinstalled all the dependencies, and still doesn't work. It is so weird because there haven't been any changes to the script ever since that change nor any updates to ts-simple-ast or TypeScript.

I'm going to need more time to test this to try to find what's causing the issue because it doesn't make any sense. I'll get back to you soon. Thanks for the quick response.

**Comment by dsherret** [comment] 2018-10-24 17:19
That is strange! I'm not too familiar with this part of the typescript compiler API. Maybe I'll ask someone on the ts team what the proper thing is to do here, but for now you may want to resort to just manipulating the string :/

**Comment by elclanrs** [comment] 2018-10-25 19:29
@dsherret I was able to reproduce it. It took me a while to figure out the issue, but I have a simple example so you can see the bug.

1) Clone this repo https://github.com/elclanrs/ast-qualified-name-bug
2) Run `node ast.js`

Notice that the output is wrong:

```
size : AvatarSize
avatarSize : import("/home/elclanrs/Documents/sandbox/ast-test/src/app/avatar/avatar.component").AvatarSize
```

The first input type is correct `size: AvatarSize`, but notice that the second input is not correct, and in addition the outputting the wrong type (it should be `avatarSize: CardAvatarSize`), it also outputs the full qualified name despite using `.getText(prop)`.

My guess is this is some cache invalidation issue or string manipulation issue where the text of the type is matched loosely and it pulls the wrong type for the second property, matching `AvatarSize` instead of `CardAvatarSize` from the cache.

Any ideas on how to resolve this issue?

**Comment by elclanrs** [comment] 2018-10-26 11:02
I've done some more experimentation, and it seems like the bug can be tracked down to `getTypeAtLocation`. You can see that the `type` in the expression below is already wrong:

```
const type = prop.context.typeChecker.compilerObject.getTypeAtLocation(prop.compilerNode);
```

While `prop` contains the right type, `getTypeAtLocation` returns the wrong type.

TypeScript seems to think that since the `CardAvatarSize` has the same type as `AvatarSize` it should grab `AvatarSize`. I know because if I change the type of `CardAvatarSize` to something slightly different like `CardAvatarSize = 'sm' | 'md' | 'lg'` then it reports the correct type.

This is so confusing... Is TypeScript trying to be too smart, or is there something that says that two union types that are the same but have different names must be resolved to the first encountered type that matches?

**Comment by dsherret** [comment] 2018-10-27 22:40
That's very interesting! It seems what matters here is what type is requested first to the type checker and that's the main problem here. I bet that's probably by design, but opened #480 to investigate further.

Closing this for now.

**Closed** 2021-04-03 17:15 UTC
Labels: question
