### ISSUE TITLE
is it possiable implements " transpileOnly " when project.emit()

### ISSUE THREAD

**Issue by WanderWang** [dsherret/ts-morph#602] opened 2019-04-04 13:30 UTC
**Is your feature request related to a problem? Please describe.**

I've wrote a toolkit with these features:
1. generate typescript code via ts-morph API ( such as   sourceFile.createClass )
2. emit javascript code for runtime

when step 1 create a very huge project  , it emit very slow in emit javascript code  because of type checking .

**Describe the solution you'd like**

add a flag called "translateOnly" to ignore type checking ( such as transpileOnly in ts-loader  https://www.npmjs.com/package/ts-loader )

**Describe alternatives you've considered**

**Comment by dsherret** [comment] 2019-04-04 23:42
Internally that `transpileOnly` flag is probably using `ts.transpileModule`. That actually uses `Program#emit`, which is what this library uses when you call `emit` (https://github.com/Microsoft/TypeScript/blob/865b3e786277233585e1586edba52bf837b61b71/src/services/transpile.ts#L26).

I don't believe that `emit` actually does much type checking, but it might do a bit of `declaration` is set to `true` and a few other compile options. You might want to look through that definition of `transpileModule` to see if you can get any hints for some other speed ups.

To speed this up considerably, what would help is to make it asynchronous so that it can benefit from parallel work. The compiler API is synchronous by design, but there is a `writeFile` callback that I can take advantage of to make it asynchronous. I've opened #603 and that will be in version 2.0.

**Comment by dsherret** [comment] 2019-04-05 02:00
@WanderWang Implemented #602. It will be in 2.0. That will give a big performance boost.

Actually, maybe `emit` is slow because the program has all the source files in it.

Maybe try setting these compiler options to see if it speeds things up? `{ noResolve: true, isolatedModules: true }`. If not, I'll create an additional method that uses `ts.transpileModule`.

**Comment by dsherret** [comment] 2019-09-21 22:14
Closing for now.

**Closed by dsherret** 2019-09-21 22:14 UTC
Labels: awaiting feedback, performance
