### ISSUE TITLE
Getting full name of property/type

### ISSUE THREAD

**Issue by dmeagor** [dsherret/ts-morph#105] opened 2017-10-25 15:51 UTC
I'm currently using the findReferences() method as part of a refactoring tool I'm creating to remove namespaces from a large project.

This method correctly finds all of the project references however it only returns the part being searched and does not include the namespaces to the left so I am unable to rewrite them.  Grabbing all the names to the left where they exist has proven to be far more difficult than I expected.

For example, the findReferences() return "something" rather than "foo.bar.something".

After trying various combinations of getParent, getAncestors and getPreviousSiblings I've been unable to get something that reliably pulls everything from the left (leaving any class properties on the right.)  

I tried something like this with very limited success.
```
        var node=element.getNode();
        
        if (TypeGuards.isTypeReferenceNode(node) || TypeGuards.isPropertyAccessExpression(node)){
            //property with no left namespace, leave alone.  broken DOESN'T seem to pick up all single names
            console.log("nochange: ", node.getKindName(), node.getText());            
        } else {
            var ancestor = node.getFirstAncestorByKind(ts.SyntaxKind.TypeReference);
            if (ancestor){
                    //appears to work.
                    ancestor.replaceWithText(getNewQualifiedname(ancestor.getText()))                   
            } else {
                var ancestor2 = node.getFirstAncestorByKind(ts.SyntaxKind.PropertyAccessExpression);
                if (ancestor2){
                        //not much success here.
                        ancestor2.replaceWithText(getNewQualifiedname(ancestor2.getText()))
                }
            }
```

**Comment by dsherret** [comment] 2017-10-25 21:41
Right now `findReferences` uses a method from the TypeScript compiler to get the references. This will return a range with the reference and in scenarios with a fully qualified name, it will return the more specific identifier. Note that there's a bug related to `.getNode()` (#106), but in the scenario with a "left namespace" I believe it's returning the expected result. I actually think #106 might affect your first if statement in some scenarios. Sorry about that, but this might break in a future build in order to be correct.

From the identifier, you will have to go up the tree until you reach the top-most `PropertyAccessExpression`. I'm adding something in #107 so that you will only have to do:

```typescript
const ancestor2 = this.getParentWhileKind(ts.SyntaxKind.PropertyAccessExpression);
```

That will keep getting the parent while it's a `ts.SyntaxKind.PropertyAccessExpression`.

**Comment by dsherret** [comment] 2017-10-26 15:19
@dmeagor in 0.79.0 you should be able to do the following:

```typescript
const node = element.getNode(); // this should be the identifier... previously it was a bug fixed in #106

const ancestor = node.getParentWhileKind(ts.SyntaxKind.TypeReference);
const ancestor2 = node.getParentWhileKind(ts.SyntaxKind.PropertyAccessExpression);
```

By the way, make sure to use an [ast viewer](https://dsherret.github.io/ts-simple-ast/setup/ast-viewers) to help figure out the relationship between the nodes.

**Comment by dmeagor** [comment] 2017-10-26 16:00
Thanks for trying but I don't believe that's how the names work.

I ran your code above in place of my own and it failed to work for about 90% of the references.

I ran getParent.getKind() on the missing ones and it shows things like classDeclarations, FirstNode, InterfaceDeclaration and CallExpression.  The propertyAccessExpressions that did return non-null output huge chunks of source code when I ran gettext().

If I'm understanding the AST correctly you need to go up to the nearest TypeReference or PropertyAccessExpression, but you don't know what you're looking for in advance so I think it needs to abort somehow if it's gone too far.  It appears to need a list of things it can safely step over and another list of things that you might want to find.

That's my best guess anyway.

**Comment by dsherret** [comment] 2017-10-26 16:15
Can you provide a simple specific scenario along with the actual and expected output? We can work through them one by one.

**Comment by dmeagor** [comment] 2017-10-26 16:37
Most common one to appear is FirstNode.

```
//file containing reference
//C:/Users/dmeag/Source/Repos/test/VideoTour/Data/IVideoTour.ts
    export interface IVideoTour {
        thing: shout.common.carrot.something;
    }
```

```
        const node = element.getNode();
        const ancestor = node.getParentWhileKind(ts.SyntaxKind.TypeReference);
        const ancestor2 = node.getParentWhileKind(ts.SyntaxKind.PropertyAccessExpression);

        if (ancestor)
          console.log("tr: ", referenceSourceFilePath, ancestor.getKindName(), ancestor.getText());          
        else if (ancestor2)
            console.log("pae: ", referenceSourceFilePath, ancestor2, ancestor2.getText());
        else
            console.log("error: ", referenceSourceFilePath,node.getParent().getKindName(),node.getText() );
    

//produces 
// error:  C:/Users/dmeag/Source/Repos/test/VideoTour/Data/IVideoTour.ts FirstNode something IVideoTour

```

**Comment by dmeagor** [comment] 2017-10-26 16:51
There was a small typo in my PAE console log.  that one might actually be ok after all.

I've figured out that the other things like CallExpression, Class Decoration etc. are caused by getNode now returning an identifier rather then either TypeReference or PropertyAccessExpression which I had a separate check for at the top.

**Comment by dsherret** [comment] 2017-10-26 20:16
I've wondered what FirstNode is as well before. It's because in the `SyntaxKind` enum, `FirstNode` and `QualifiedName` have the same value, so `FirstNode` overwrites `QualifiedName` because it comes afterwards:

```typescript
enum SyntaxKind {
    // ...omitted...
    QualifiedName = 143,
    // ...omitted...
    FirstNode = 143,
}
```

So for the example you gave, this is what the tree looks like:

![image](https://user-images.githubusercontent.com/1609021/32074822-92638c3a-ba68-11e7-8eb8-499c0e0c0fd7.png)

So actually, you want to go up the tree by `QualifiedName`/`FirstNode`:

```typescript
const ancestor = node.getParentWhileKind(ts.SyntaxKind.QualifiedName);
```

**Comment by dmeagor** [comment] 2017-10-26 21:00
Just before I saw this message I got it to work like this.  I guess I need to modify it to go up the qualified names first then grab the type reference after.   Strangely though it does appear to work.  It produces a mixture of TR and QN results and no unhandled error ones as before.

I'm using let left = ancestorPAE.getChildrenOfKind(ts.SyntaxKind.Identifier)[0]; to grab the names to the left of the . so as not to pick up class properties etc.  Also seems to work.


```
const node = element.getNode();
const ancestorQN = node.getParentWhileKind(ts.SyntaxKind.QualifiedName);
const ancestorTR = node.getParentWhileKind(ts.SyntaxKind.TypeReference);            
const ancestorPAE = node.getParentWhileKind(ts.SyntaxKind.PropertyAccessExpression);
            
if (ancestorTR)
        console.log("tr: ", refModule, ancestorTR.getKindName(), ancestorTR.getText());    
else if (ancestorQN)
        console.log("qn: ",  refModule, ancestorQN.getKindName(), ancestorQN.getText());  
else if (ancestorPAE){
        let left = ancestorPAE.getChildrenOfKind(ts.SyntaxKind.Identifier)[0];
        if (left)
            console.log("pae: ",  refModule, ancestorPAE.getKindName(), ancestorPAE.getText(), left.getText());
        else
            console.log("pae: ",  refModule, ancestorPAE.getKindName(), ancestorPAE.getText());
}
else
        console.log("error: ",  refModule,node.getKindName(), node.getParent().getKindName(),node.getText() );
```

I think I might actually be done after this!  I did find one very small issue when adding imports, I it appears to be adding some kind of special character after them (perhaps they're being inserted before the BOM or something like that?)  I'll investigate and post an issue if I can recreate it later.

**Comment by dsherret** [comment] 2017-10-28 02:50
Nice, I'm glad it's mostly working out! Let me know what you find about the special character being introduced when you get a chance. I will maybe spend some time on it this weekend to try to reproduce it.

By the way, I created a very simple web-based AST viewer that you can use to help understand the tree. It's very simple for now, but shows the relationship between the nodes (it took me about 6 hours to do). I'll work on improving it more in the future: https://dsherret.github.io/ts-ast-viewer/

**Comment by skellock** [comment] 2017-10-29 16:35
@dsherret that is **really** well done

**Comment by dsherret** [comment] 2017-10-29 17:06
@skellock thanks! I hope it will be useful.

I just fixed a bug where some node properties would not expand when clicked. Should be good now.

**Comment by dsherret** [comment] 2017-11-13 00:49
I don't believe there's anything still outstanding in this issue so I'm closing it. Please reopen it if that's not correct.

**Closed** 2021-04-03 17:14 UTC
Labels: question
